Build started...
Build succeeded.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE customers (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cpf text NULL,
    nome text NULL,
    numfone1 text NULL,
    numfone2 text NULL,
    endereco text NULL,
    email text NULL,
    CONSTRAINT "PK_customers" PRIMARY KEY (id)
);

CREATE TABLE events (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome text NULL,
    datainicio timestamp without time zone NOT NULL,
    datatermino timestamp without time zone NOT NULL,
    local text NULL,
    capacidade integer NOT NULL,
    quorum integer NOT NULL,
    orcamentoprevio numeric NOT NULL,
    valoringresso numeric NOT NULL,
    cronograma text NULL,
    status integer NOT NULL,
    CONSTRAINT "PK_events" PRIMARY KEY (id)
);

CREATE TABLE paymenttypes (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description integer NOT NULL,
    CONSTRAINT "PK_paymenttypes" PRIMARY KEY (id)
);

CREATE TABLE providers (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NULL,
    CONSTRAINT "PK_providers" PRIMARY KEY (id)
);

CREATE TABLE users (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login text NULL,
    password text NULL,
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

CREATE TABLE inscription (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    valortotal numeric NOT NULL,
    valorrecebido numeric NOT NULL,
    tipopagamentoid integer NULL,
    customerid integer NULL,
    eventid integer NULL,
    CONSTRAINT "PK_inscription" PRIMARY KEY (id),
    CONSTRAINT "FK_inscription_customers_customerid" FOREIGN KEY (customerid) REFERENCES customers (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inscription_events_eventid" FOREIGN KEY (eventid) REFERENCES events (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inscription_paymenttypes_tipopagamentoid" FOREIGN KEY (tipopagamentoid) REFERENCES paymenttypes (id) ON DELETE RESTRICT
);

CREATE TABLE agreement (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    providerid integer NULL,
    eventid integer NULL,
    CONSTRAINT "PK_agreement" PRIMARY KEY (id),
    CONSTRAINT "FK_agreement_events_eventid" FOREIGN KEY (eventid) REFERENCES events (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_agreement_providers_providerid" FOREIGN KEY (providerid) REFERENCES providers (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_agreement_eventid" ON agreement (eventid);

CREATE INDEX "IX_agreement_providerid" ON agreement (providerid);

CREATE INDEX "IX_inscription_customerid" ON inscription (customerid);

CREATE INDEX "IX_inscription_eventid" ON inscription (eventid);

CREATE INDEX "IX_inscription_tipopagamentoid" ON inscription (tipopagamentoid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200302212419_InitialCreate', '3.1.2');


