// <auto-generated />
using System;
using Escalada.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace escalada.Migrations
{
    [DbContext(typeof(EscaladaContext))]
    partial class EscaladaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Escalada.Models.Agreement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Eventid")
                        .HasColumnType("integer");

                    b.Property<int?>("providerIdid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Eventid");

                    b.HasIndex("providerIdid");

                    b.ToTable("agreement");
                });

            modelBuilder.Entity("Escalada.Models.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long[]>("cpf")
                        .HasColumnType("bigint[]");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("endereco")
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<long[]>("numFone1")
                        .HasColumnType("bigint[]");

                    b.Property<long[]>("numFone2")
                        .HasColumnType("bigint[]");

                    b.HasKey("id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Escalada.Models.Event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("capacidade")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("dataTermino")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("local")
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<decimal>("orcamentoPrevio")
                        .HasColumnType("numeric");

                    b.Property<long>("quorum")
                        .HasColumnType("bigint");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<decimal>("valorIngresso")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Escalada.Models.Inscription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Customerid")
                        .HasColumnType("integer");

                    b.Property<int?>("Eventid")
                        .HasColumnType("integer");

                    b.Property<int?>("tipoPagamentoIdid")
                        .HasColumnType("integer");

                    b.Property<decimal>("valorRecebido")
                        .HasColumnType("numeric");

                    b.Property<decimal>("valorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("Customerid");

                    b.HasIndex("Eventid");

                    b.HasIndex("tipoPagamentoIdid");

                    b.ToTable("inscription");
                });

            modelBuilder.Entity("Escalada.Models.PaymentType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("paymentTypes");
                });

            modelBuilder.Entity("Escalada.Models.Provider", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("providers");
                });

            modelBuilder.Entity("Escalada.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("login")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Escalada.Models.Agreement", b =>
                {
                    b.HasOne("Escalada.Models.Event", null)
                        .WithMany("fornecedores")
                        .HasForeignKey("Eventid");

                    b.HasOne("Escalada.Models.Provider", "providerId")
                        .WithMany("agreementId")
                        .HasForeignKey("providerIdid");
                });

            modelBuilder.Entity("Escalada.Models.Inscription", b =>
                {
                    b.HasOne("Escalada.Models.Customer", null)
                        .WithMany("inscricoes")
                        .HasForeignKey("Customerid");

                    b.HasOne("Escalada.Models.Event", null)
                        .WithMany("inscricoes")
                        .HasForeignKey("Eventid");

                    b.HasOne("Escalada.Models.PaymentType", "tipoPagamentoId")
                        .WithMany()
                        .HasForeignKey("tipoPagamentoIdid");
                });
#pragma warning restore 612, 618
        }
    }
}
